In [6]:
## imports 
import pandas as pd
import numpy as np
import yaml
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

# comment these out if you don't have plotnine--not essential here/only used once
import matplotlib.pyplot as plt
import plotnine
from plotnine import *

## way to connect to mysql 
## if you need to install
## uncomment this line:
! pip install mysql-connector-python
import mysql.connector

## function to feed path name to load
## credentials
def load_creds(path: str):
    with open(path, 'r') as stream:
        try:
            creds = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    return(creds)

pd.options.display.max_rows = 999
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.3.0-cp310-cp310-win_amd64.whl.metadata (7.5 kB)
Downloading mysql_connector_python-9.3.0-cp310-cp310-win_amd64.whl (16.4 MB)
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
   -------------- ------------------------- 5.8/16.4 MB 32.2 MB/s eta 0:00:01
   --------------------------------- ------ 13.6/16.4 MB 34.3 MB/s eta 0:00:01
   ---------------------------------------- 16.4/16.4 MB 31.3 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.3.0

# Preliminary: define connection and read sample of data

In [8]:
## read in creds; change the path name if stored
## elsewhere
creds = load_creds("09_db_cred.yaml")
creds

{'practice_database': {'user': 'qss20',
  'password': 'xtPdDZHnxKMFSD5RyP',
  'port': 3306,
  'database': 'sentencing',
  'host': 'qss20-7570-db.c.dartmouth.edu'}}

# Activity 1

1. Create a new column -- `in_chicago` when pulling from the `caseinit` table that takes on the value of "YES" if INCIDENT_CITY = Chicago; "NO" otherwise (which represents incidents in Cook County suburbs outside the city limits);  and pull the table. Use `crosstabs` to confirm that this worked
2. Repeat step 1 but also filter out blank strings (`INCIDENT_CITY` == "")
3. Use `where` to row filter to initiations in Chicago and use group by to find the count of cases diverted and not diverted (`is_in_diversion`); pull the table with those counts
4. Modify the query in step 3 to find the proportion of cases in chicago diverted (hint you made need to use case when in a subquery)
6. Modify the query in step 4 to find the proportion of cases in chicago versus cases not in chicago sent to diversion

In [31]:
# your code here 1
cnx = mysql.connector.connect(user=creds['practice_database']['user'], 
                            password=creds['practice_database']['password'],
                            port=creds['practice_database']['port'],
                            database= creds['practice_database']['database'],
                            host = creds['practice_database']['host'])
cnx

new_col_q = """
SELECT *,
       CASE
         WHEN INCIDENT_CITY = 'Chicago' THEN 'YES'
         ELSE 'NO'
       END AS in_chicago_1
FROM   caseinit 
"""

new_col_d = pd.read_sql_query(new_col_q, cnx)
new_col_d
pd.crosstab(new_col_d['INCIDENT_CITY'], new_col_d['in_chicago_1'])

,CASE_ID,CASE_PARTICIPANT_ID,RECEIVED_DATE,OFFENSE_CATEGORY,PRIMARY_CHARGE_FLAG,CHARGE_ID,CHARGE_VERSION_ID,DISPOSITION_CHARGED_OFFENSE_TITLE,CHARGE_COUNT,DISPOSITION_DATE,...,LAW_ENFORCEMENT_AGENCY,LAW_ENFORCEMENT_UNIT,ARREST_DATE,FELONY_REVIEW_DATE,FELONY_REVIEW_RESULT,ARRAIGNMENT_DATE,UPDATED_OFFENSE_CATEGORY,is_in_diversion,in_chicago,in_chicago_1
0,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242195814523,155656315869,FIRST DEGREE MURDER,2,12/17/2014 12:00:00 AM,...,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None,NO
1,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242198287388,131513547452,HOME INVASION,14,12/17/2014 12:00:00 AM,...,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None,NO
2,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242351605056,176626576281,FIRST DEGREE MURDER,4,12/17/2014 12:00:00 AM,...,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None,NO
3,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242352841488,176617824190,FIRST DEGREE MURDER,5,12/17/2014 12:00:00 AM,...,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None,NO
4,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242356550787,131238606761,HOME INVASION,13,12/17/2014 12:00:00 AM,...,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272289,597320386308,452719800958,07/18/2022 12:00:00 AM,Retail Theft,True,11294724616133,1148300237684,RETAIL THEFT,1,09/02/2022 12:00:00 AM,...,CHICAGO PD,,07/18/2022 09:20:00 AM,07/18/2022 12:00:00 AM,Approved,09/02/2022 12:00:00 AM,Retail Theft,True,None,YES
272290,597328542979,452727325242,07/18/2022 12:00:00 AM,Aggravated Fleeing and Eluding,True,11295052270826,1148334245809,AGGRAVATED FLEEING OR ATTEMPT TO ELUDE A PEACE...,1,09/06/2022 12:00:00 AM,...,EVERGREEN PARK PD,,07/18/2022 11:11:00 PM,07/18/2022 12:00:00 AM,Approved,09/06/2022 12:00:00 AM,Aggravated Fleeing and Eluding,False,None,NO
272291,597341166398,452739650297,07/19/2022 12:00:00 AM,Criminal Damage to Property,True,11295731072434,1148405887926,CRIMINAL DAMAGE TO GOVERNMENT SUPPORTED PROPERTY,1,08/23/2022 12:00:00 AM,...,COOK COUNTY SHERIFF (IL0160000),,,08/02/2022 12:00:00 AM,Approved,08/17/2022 12:00:00 AM,Criminal Damage to Property,False,None,YES
272292,597341166398,452739650297,07/19/2022 12:00:00 AM,Criminal Damage to Property,True,11295731072434,1148405887926,CRIMINAL DAMAGE TO GOVERNMENT SUPPORTED PROPERTY,1,08/23/2022 12:00:00 AM,...,COOK COUNTY SHERIFF (IL0160000),,,08/02/2022 12:00:00 AM,Approved,08/17/2022 12:00:00 AM,Criminal Damage to Property,False,None,YES
272293,597406808178,452817755138,07/23/2022 12:00:00 AM,UUW - Unlawful Use of Weapon,True,11310189917611,1149901120181,AGGRAVATED UNLAWFUL USE OF WEAPON,1,08/31/2022 12:00:00 AM,...,PARK FOREST PD,,07/23/2022 05:09:00 AM,07/23/2022 12:00:00 AM,Approved,08/30/2022 12:00:00 AM,UUW - Unlawful Use of Weapon,False,None,NO

in_chicago_1              NO     YES
INCIDENT_CITY
                       20557       0
Addison                    2       0
Albers                     1       0
Algonquin                  3       0
Alsip                    568       0
Antioch                    2       0
Arlington Heights       1291       0
Aurora                     3       0
Barrington               136       0
Barrington Hills          16       0
Bartlett                 241       0
Bedford Park             335       0
Beecher                    1       0
Bellwood                 848       0
Bensenville                3       0
Berkeley                 160       0
Berwyn                  2152       0
Bloomingdale               1       0
Bloomington                1       0
Blue Island             1192       0
Bluff Springs              1       0
Bolingbrook                5       0
Bourbonnais                1       0
Braidwood                  1       0
Bridgeview               704       0
Brighton                   1       0
Broadview                558       0
Brookfield               338       0
Brookport                  1       0
Buffalo Grove            245       0
Burbank                  575       0
Burlington                 1       0
Burnham                  238       0
Burr Ridge                57       0
Calumet City            1972       0
Calumet Park             434       0
Cambria                    1       0
Canton                     1       0
Cary                       1       0
Cedar Lake                 2       0
Channahon                  2       0
Chestnut                   1       0
Chicago                    0  173573
Chicago Heights         2039       0
Chicago Ridge            472       0
Cicero                  4263       0
Cimic                      1       0
Country Club Hills       529       0
Countryside              223       0
Crestwood                374       0
Crete                      2       0
Darien                     1       0
Deerfield                 59       0
DesPlaines              1374       0
Dixmoor                   98       0
Dixon                      1       0
Dolton                  1209       0
Downers Grove              4       0
East Chicago               2       0
East Hazel Crest         174       0
Elgin                    499       0
Elk Grove Village        767       0
Elkhart                    1       0
Elmhurst                  24       0
Elmwood                    1       0
Elmwood Park             660       0
Evanston                1772       0
Evansville                 1       0
Evergreen Park          1414       0
Ewing                      3       0
Flossmoor                297       0
Ford Heights             488       0
Forest City                1       0
Forest Park             1502       0
Forest View               56       0
Frankfort                  1       0
Franklin Park            734       0
Glen Ellyn                 2       0
Glencoe                  118       0
Glendale Heights           1       0
Glenview                 694       0
Glenwood                 258       0
Golf                       1       0
Griffith                   1       0
Gurnee                     6       0
Halstead                   1       0
Hammond                    5       0
Hanover                    1       0
Hanover Park             847       0
Harvey                  2080       0
Harwood Heights          264       0
Hazel Crest              399       0
Hickory Hills            311       0
Highland Park              1       0
Highwood                   1       0
Hillside                 526       0
Hinckley                   1       0
Hines                     45       0
Hinsdale                  23       0
Hobart                     1       0
Hodgkins                 395       0
Hoffman                    1       0
Hoffman Estates         1048       0
Homer Glen                 2       0
Hometown                  86       0
Homewood                1126       0
Indian Head Park          43       0
Ingleside                  2       0
Inverness                 11       0
Itasca                     1       0
Jefferson Park             9       0
Joliet                     4       0
Justice                  443       0
Kenilworth                14       0
LaGrange                 186       0
LaGrange Highlands         8       0
LaGrange Park             79       0
Lake Barrington            1       0
Lake Bluff                 2       0
Lake In The Hills          1       0
Lake Zurich                2       0
Lansing                 1072       0
Lemont                   296       0
Lincolnwood              352       0
Lombard                    1       0
Lynwood                  260       0
Lyons                    287       0
Markham                  885       0
Marseilles                 2       0
Matteson                1065       0
Maywood                 1526       0
McCook                    65       0
Melrose Park            1226       0
Merrionette Park          47       0
Midlothian               568       0
Minneapolis                1       0
Mokena                     1       0
Monee                      1       0
Morton                     2       0
Morton Grove             386       0
Mount Greenwood           10       0
Mount Prospect          1195       0
Mundelein                  1       0
Munster                    1       0
Naperville                 4       0
New Lenox                  2       0
Niles                    799       0
Norridge                 477       0
North Chicago              1       0
North Riverside          879       0
Northbrook               608       0
Northfield                83       0
Northlake                635       0
Oak Brook                  9       0
Oak Brook Mall             1       0
Oak Forest               439       0
Oak Lawn                1775       0
Oak Park                1749       0
Oakbrook Terrace           1       0
Olympia FIELDS             2       0
Olympia Fields           149       0
Orland Hills             115       0
Orland Park             1870       0
Oswego                     1       0
Palatine                1359       0
Palos Heights            181       0
Palos Hills              218       0
Palos Park                90       0
Park City                  5       0
Park Forest              908       0
Park Ridge               329       0
Phoenix                   73       0
Pinckneyville              1       0
Plato Center               1       0
Pontiac                    3       0
Portage                    1       0
Posen                    345       0
Prospect Heights         436       0
Ransom                     1       0
Richton Park             347       0
River Forest             753       0
River Grove              287       0
Riverdale                766       0
Riverside                358       0
Robbins                  289       0
Rockford                   3       0
Rolling Meadows          539       0
Roselle                   43       0
Rosemont                 760       0
Round Lake                 2       0
Saint Charles              3       0
Sauget                     1       0
Sauk Village             875       0
Savanna                    1       0
Schaumburg              1850       0
Schererville               1       0
Schiller Park            589       0
Sheridan                   1       0
Skokie                  1532       0
South Barrington         191       0
South Bend                 1       0
South Chicago Heights    145       0
South Holland            621       0
Steger                    91       0
Steward                    1       0
Stickney                 167       0
Stone Park               193       0
Streamwood              1198       0
Summit                   438       0
Summit Argo                4       0
Thornton                  42       0
Tinley Park              735       0
University Park           10       0
Vernon Hills               1       0
Waukegan                   5       0
West Chicago               1       0
West Dundee                1       0
Westchester              341       0
Western Springs           52       0
Westmont                   1       0
Wheaton                    4       0
Wheeling                1094       0
Willow Springs            82       0
Willowbrook                2       0
Wilmette                 333       0
Winnetka                 129       0
Wood Dale                  3       0
Woodstock                  1       0
Worth                    284       0

In [21]:
#cross_tab = pd.crosstab(new_col_d.INCIDENT_CITY, new_col_d.in_chicago)

In [22]:
# your code here 2
new_col_q = """
SELECT *,
       CASE
         WHEN INCIDENT_CITY = 'Chicago' THEN 'YES'
         ELSE 'NO'
       END AS in_chicago
FROM   caseinit 
WHERE INCIDENT_CITY > ""
"""

new_col_d = pd.read_sql_query(new_col_q, cnx)
new_col_d

,CASE_ID,CASE_PARTICIPANT_ID,RECEIVED_DATE,OFFENSE_CATEGORY,PRIMARY_CHARGE_FLAG,CHARGE_ID,CHARGE_VERSION_ID,DISPOSITION_CHARGED_OFFENSE_TITLE,CHARGE_COUNT,DISPOSITION_DATE,...,LAW_ENFORCEMENT_AGENCY,LAW_ENFORCEMENT_UNIT,ARREST_DATE,FELONY_REVIEW_DATE,FELONY_REVIEW_RESULT,ARRAIGNMENT_DATE,UPDATED_OFFENSE_CATEGORY,is_in_diversion,in_chicago,in_chicago
0,288677981683,95130773152,08/13/2006 12:00:00 AM,PROMIS Conversion,True,8889814596849,969426374459,DUI LIC SUSP OR REVOKED,1,01/28/2015 12:00:00 AM,...,OAK PARK PD,,08/13/2006 02:53:00 AM,08/13/2006 12:00:00 AM,Charge(S) Approved,10/03/2012 12:00:00 AM,PROMIS Conversion,False,None,NO
1,289906337472,103165877915,06/18/2007 12:00:00 AM,Sex Crimes,False,6339673180732,590301665421,CRIMINAL SEXUAL ASSAULT,5,12/09/2013 12:00:00 AM,...,HARVEY POLICE DEPARTMENT,,08/30/2011 02:00:00 PM,08/30/2011 12:00:00 AM,Approved,10/06/2011 12:00:00 AM,Sex Crimes,False,None,NO
2,291517474172,103760942634,08/20/2008 12:00:00 AM,PROMIS Conversion,True,6363523969467,608781580816,AGGRAVATED FLEEING OR ATTEMPT TO ELUDE A PEACE...,1,01/18/2012 12:00:00 AM,...,MORTON GROVE PD,,08/20/2008 12:00:00 AM,08/20/2008 12:00:00 AM,Approved Arrest War,08/02/2010 12:00:00 AM,PROMIS Conversion,False,None,NO
3,291824708774,103847218017,09/06/2008 12:00:00 AM,PROMIS Conversion,True,6786219541928,701030496794,AGGRAVATED DRIVING UNDER THE INFLUENCE OF ALCOHOL,1,07/11/2012 12:00:00 AM,...,CHICAGO PD,,09/06/2008 12:45:00 AM,09/06/2008 12:00:00 AM,Charge(S) Approved,09/08/2011 12:00:00 AM,PROMIS Conversion,False,None,YES
4,292499187771,103592823349,02/26/2010 12:00:00 AM,PROMIS Conversion,True,8223789049105,866910505404,UNLAWFUL USE OF A WEAPON,1,08/22/2011 12:00:00 AM,...,CHICAGO POLICE DEPT,,02/25/2010 09:49:00 PM,02/26/2010 12:00:00 AM,Sf,05/28/2010 12:00:00 AM,PROMIS Conversion,False,None,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251732,597320386308,452719800958,07/18/2022 12:00:00 AM,Retail Theft,True,11294724616133,1148300237684,RETAIL THEFT,1,09/02/2022 12:00:00 AM,...,CHICAGO PD,,07/18/2022 09:20:00 AM,07/18/2022 12:00:00 AM,Approved,09/02/2022 12:00:00 AM,Retail Theft,True,None,YES
251733,597328542979,452727325242,07/18/2022 12:00:00 AM,Aggravated Fleeing and Eluding,True,11295052270826,1148334245809,AGGRAVATED FLEEING OR ATTEMPT TO ELUDE A PEACE...,1,09/06/2022 12:00:00 AM,...,EVERGREEN PARK PD,,07/18/2022 11:11:00 PM,07/18/2022 12:00:00 AM,Approved,09/06/2022 12:00:00 AM,Aggravated Fleeing and Eluding,False,None,NO
251734,597341166398,452739650297,07/19/2022 12:00:00 AM,Criminal Damage to Property,True,11295731072434,1148405887926,CRIMINAL DAMAGE TO GOVERNMENT SUPPORTED PROPERTY,1,08/23/2022 12:00:00 AM,...,COOK COUNTY SHERIFF (IL0160000),,,08/02/2022 12:00:00 AM,Approved,08/17/2022 12:00:00 AM,Criminal Damage to Property,False,None,YES
251735,597341166398,452739650297,07/19/2022 12:00:00 AM,Criminal Damage to Property,True,11295731072434,1148405887926,CRIMINAL DAMAGE TO GOVERNMENT SUPPORTED PROPERTY,1,08/23/2022 12:00:00 AM,...,COOK COUNTY SHERIFF (IL0160000),,,08/02/2022 12:00:00 AM,Approved,08/17/2022 12:00:00 AM,Criminal Damage to Property,False,None,YES
251736,597406808178,452817755138,07/23/2022 12:00:00 AM,UUW - Unlawful Use of Weapon,True,11310189917611,1149901120181,AGGRAVATED UNLAWFUL USE OF WEAPON,1,08/31/2022 12:00:00 AM,...,PARK FOREST PD,,07/23/2022 05:09:00 AM,07/23/2022 12:00:00 AM,Approved,08/30/2022 12:00:00 AM,UUW - Unlawful Use of Weapon,False,None,NO

In [32]:
# your code here 3: Use where to row filter to initiations in Chicago and use group by to find the count of 
# cases diverted and not diverted (is_in_diversion); pull the table with those counts
q = """
SELECT is_in_diversion, Count(*) as num_cases
FROM   caseinit 
WHERE INCIDENT_CITY = 'Chicago'
GROUP BY is_in_diversion
"""

new_col_d = pd.read_sql_query(q, cnx)
new_col_d

  is_in_diversion  num_cases
0           False     167171
1            True       6402

In [36]:
# your code here 4: 4. Modify the query in step 3 to find the proportion of cases in chicago diverted (hint you made need to use case when
# in a subquery)
prop_div = """
SELECT 
    SUM(CASE WHEN is_in_diversion = 'True' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) AS proportion_diverted
FROM (
    SELECT *,
           CASE 
               WHEN INCIDENT_CITY = 'Chicago' THEN 'YES' 
               ELSE 'NO' 
           END AS in_chicago2
    FROM caseinit
) AS tmp
WHERE in_chicago2 = 'YES';
"""

prop_div_d = pd.read_sql_query(prop_div, cnx)
prop_div_d

   proportion_diverted
0              0.03688

In [38]:
# your code here 5: 6. Modify the query in step 4 to find the proportion of cases in chicago versus cases not in chicago sent to diversion 
query_propdiv_compare = """
SELECT 
    AVG(is_div_bool) as prop_div, 
    in_chicago_1
FROM  (
    SELECT 
        *,
        CASE 
            WHEN is_in_diversion = 'True' THEN 1
            ELSE 0
        END as is_div_bool,
        CASE 
            WHEN INCIDENT_CITY = 'Chicago' THEN 'Yes'
            ELSE 'No'
        END AS in_chicago_1
    FROM caseinit) AS d
WHERE INCIDENT_CITY <> ''
GROUP BY in_chicago_1
"""
prop_div_compare = pd.read_sql_query(query_propdiv_compare, cnx)
prop_div_compare

   prop_div in_chicago_1
0    0.0470           No
1    0.0369          Yes

# Activity 2 

1. Use the following crosswalk and the `CASE` variable in the `divert` table to create a new variable `DIVERSION_PROGRAM_TEXT` that spells out the diversion programs
    - DC: Drug Court

    - DDPP: Drug Deferred Prosecution

    - DS: Drug School

    - RJCC: Restorative Justice

    - MHC: Mental Health Court

    - VC: Veteran Court

2. Build on the query from step 1 to filter to Narcotics as the `UPDATED_OFFENSE_CATEGORY` and Black or White defendants (based on race in the diversions table) (hint: you'll need to join with the caseinit table based on case_id and case_participant_id, you can do a inner join to keep only those diverted). Select the case_id, case_participant_id, case, race, and diversion_program_text columns

In [ ]:
# your code here 1
dt_type = """
CASE WHEN DIVERSION_PROGRAM = 'DC' THEN 'Drug Court', etc
"""

In [ ]:
# your code here 2
#crosstab